
package hidrocon.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HidroconWS", targetNamespace = "http://webservice.hidrocon/", wsdlLocation = "http://localhost:8080/hidroconweb/hidroconws?wsdl")
public class HidroconWS_Service
    extends Service
{

    private final static URL HIDROCONWS_WSDL_LOCATION;
    private final static WebServiceException HIDROCONWS_EXCEPTION;
    private final static QName HIDROCONWS_QNAME = new QName("http://webservice.hidrocon/", "HidroconWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/hidroconweb/hidroconws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HIDROCONWS_WSDL_LOCATION = url;
        HIDROCONWS_EXCEPTION = e;
    }

    public HidroconWS_Service() {
        super(__getWsdlLocation(), HIDROCONWS_QNAME);
    }

    public HidroconWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), HIDROCONWS_QNAME, features);
    }

    public HidroconWS_Service(URL wsdlLocation) {
        super(wsdlLocation, HIDROCONWS_QNAME);
    }

    public HidroconWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HIDROCONWS_QNAME, features);
    }

    public HidroconWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HidroconWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HidroconWS
     */
    @WebEndpoint(name = "HidroconWSPort")
    public HidroconWS getHidroconWSPort() {
        return super.getPort(new QName("http://webservice.hidrocon/", "HidroconWSPort"), HidroconWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HidroconWS
     */
    @WebEndpoint(name = "HidroconWSPort")
    public HidroconWS getHidroconWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.hidrocon/", "HidroconWSPort"), HidroconWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HIDROCONWS_EXCEPTION!= null) {
            throw HIDROCONWS_EXCEPTION;
        }
        return HIDROCONWS_WSDL_LOCATION;
    }

}
