/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CommentDetailsDialog.java
 *
 * Created on 29-nov-2011, 7:16:41
 */
package hidrocon.ui.comment.panels.dialogs;

import hidrocon.custom.dialog.HidroDialog;
import hidrocon.custom.dialog.interfaces.IEntityView;
import hidrocon.ui.comment.panels.details.CommentDetailsController;
import hidrocon.ui.comment.panels.details.CommentDetailsModel;
import hidrocon.ui.comment.panels.details.CommentDetailsView;
import hidrocon.webservice.Comment;
import java.awt.Dimension;

/**
 *
 * @author David Sáenz Tagarro
 */
public class CommentDetailsDialog extends HidroDialog implements IEntityView {

    private CommentDetailsModel model;    
    private CommentDetailsView view;
    private CommentDetailsController controller;

    /** Creates new form CommentDetailsDialog */
    public CommentDetailsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initContent();
    }
    
    private void initContent() {
        view = new CommentDetailsView();
        model = new CommentDetailsModel();
        controller = new CommentDetailsController(model, view);
        
        controller.setDialog(this);
        view.setMinimumSize(new Dimension(600,150));
        view.setMaximumSize(new Dimension(600,150));
        view.setPreferredSize(new Dimension(600,150));
        getContentPane().add(view);
        
        //HidroBlockingLayerUI layerUI = new HidroBlockingLayerUI();
        //JLayer<JPanel> jlayerMain = new JLayer<JPanel>(view, layerUI);
        //getContentPane().add(jlayerMain);
        pack();        
    }
    
    public void setMode(int mode) {
        controller.setMode(mode);
    }

    public void setEntity(Object comment) {
        controller.setComment((Comment)comment);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
