/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NeighbourMeterPanelView.java
 *
 * Created on 25-dic-2011, 6:39:12
 */
package hidrocon.ui.neighbour.meter;

import hidrocon.HidroconView;
import hidrocon.core.utils.ActionKey;
import hidrocon.custom.button.section.HidroSaveButton;
import hidrocon.custom.button.toolbar.HidroEditButton;
import hidrocon.custom.button.toolbar.HidroExitButton;
import hidrocon.component.meter.MeterNodeView;
import hidrocon.custom.button.toolbar.HidroNewButton;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author David Sáenz Tagarro
 */
public class NeighbourMeterPanelView extends javax.swing.JPanel {

    HidroNewButton newButton;
    HidroEditButton editButton;
    HidroSaveButton saveButton;
    HidroExitButton exitButton;
    
    /** Creates new form NeighbourMeterPanelView */
    public NeighbourMeterPanelView() {
        initComponents();
        initTopPanel();
        customizeComponents();
    }

    protected void customizeComponents() {
		org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(hidrocon.HidroconApp.class).getContext().getResourceMap(HidroconView.class);
        //Sections:
        //Details 2 panel:
        //meterSection.setImageIcon(new HidroMeterLegend());
        //severalDataSection.setImageIcon(new HidroSeveralDataLegend());
    }
    
	protected void initTopPanel() {
		org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(hidrocon.HidroconApp.class).getContext().getResourceMap(HidroconView.class);
		topPanel.setTitle("  " + resourceMap.getString("metertype.details.toppanel.title"));
		
        newButton = new HidroNewButton();
		editButton = new HidroEditButton();
		saveButton = new HidroSaveButton();
		exitButton = new HidroExitButton();
        
        newButton.setToolTipText(resourceMap.getString("neighbourmeter.details.toolbar.newbutton.tooltip"));
		editButton.setToolTipText(resourceMap.getString("neighbourmeter.details.toolbar.editbutton.tooltip"));
		saveButton.setToolTipText(resourceMap.getString("neighbourmeter.details.toolbar.savebutton.tooltip"));
		exitButton.setToolTipText(resourceMap.getString("neighbourmeter.details.toolbar.exitbutton.tooltip"));
        
        topPanel.addButton(newButton);
		topPanel.addButton(editButton);
		topPanel.addButton(saveButton);
        topPanel.addButton(exitButton);
	}
    
    public void writeData(List<MeterNodeView> meterViewList) {
        meterPanel.removeAll();
        for (MeterNodeView meterView : meterViewList) {
            meterPanel.add(meterView);
        }
    }    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new hidrocon.custom.panel.HidroTopPanel();
        mainPanel = new hidrocon.custom.panel.HidroMainPanel();
        meterPanel = new javax.swing.JPanel();
        left2Filler = new javax.swing.Box.Filler(new java.awt.Dimension(25, 25), new java.awt.Dimension(25, 25), new java.awt.Dimension(25, 32767));
        right2Filler = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 32767));
        bottom2Filler = new javax.swing.Box.Filler(new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25), new java.awt.Dimension(32767, 10));
        topFiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25), new java.awt.Dimension(32767, 25));

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        topPanel.setMaximumSize(new java.awt.Dimension(580, 35));
        topPanel.setName("topPanel"); // NOI18N
        add(topPanel, java.awt.BorderLayout.PAGE_START);

        mainPanel.setMaximumSize(new java.awt.Dimension(560, 575));
        mainPanel.setMinimumSize(new java.awt.Dimension(560, 575));
        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setPreferredSize(new java.awt.Dimension(560, 575));
        mainPanel.setRequestFocusEnabled(false);
        mainPanel.setLayout(new java.awt.BorderLayout());

        meterPanel.setName("meterPanel"); // NOI18N
        meterPanel.setOpaque(false);
        meterPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        mainPanel.add(meterPanel, java.awt.BorderLayout.CENTER);

        left2Filler.setName("left2Filler"); // NOI18N
        mainPanel.add(left2Filler, java.awt.BorderLayout.WEST);

        right2Filler.setName("right2Filler"); // NOI18N
        mainPanel.add(right2Filler, java.awt.BorderLayout.EAST);

        bottom2Filler.setName("bottom2Filler"); // NOI18N
        mainPanel.add(bottom2Filler, java.awt.BorderLayout.SOUTH);

        topFiller.setName("topFiller"); // NOI18N
        mainPanel.add(topFiller, java.awt.BorderLayout.PAGE_START);

        add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler bottom2Filler;
    private javax.swing.Box.Filler left2Filler;
    private hidrocon.custom.panel.HidroMainPanel mainPanel;
    private javax.swing.JPanel meterPanel;
    private javax.swing.Box.Filler right2Filler;
    private javax.swing.Box.Filler topFiller;
    private hidrocon.custom.panel.HidroTopPanel topPanel;
    // End of variables declaration//GEN-END:variables

    public void buttonActionListeners(ActionListener al) {
        newButton.setActionCommand(ActionKey.NEIGHBOUR_METER_CREATE);
		newButton.addActionListener(al);                
        editButton.setActionCommand(ActionKey.NEIGHBOUR_METER_EDIT);
		editButton.addActionListener(al);        
        saveButton.setActionCommand(ActionKey.NEIGHBOUR_METER_SAVE);
		saveButton.addActionListener(al);        
        exitButton.setActionCommand(ActionKey.NEIGHBOUR_METER_CLOSE);
		exitButton.addActionListener(al);        
    }
    
    public JPanel getMainPanel() {
        return mainPanel;
    }

}
