/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MeterPanelView.java
 *
 * Created on 06-dic-2011, 13:53:35
 */
package hidrocon.component.meter;

import hidrocon.HidroconView;
import hidrocon.core.database.neighbourmeter.entities.NeighbourMeter;
import hidrocon.core.database.neighbourmeter.entities.NeighbourMeterView;
import hidrocon.custom.button.section.HidroDeleteButton;
import hidrocon.custom.button.section.HidroSaveButton;
import hidrocon.custom.panel.HidroItemContentPanel;
import java.awt.Dimension;
import java.awt.event.ActionListener;

/**
 *
 * @author David Sáenz Tagarro
 */
public class MeterReadingPanelView extends HidroItemContentPanel {

    private HidroDeleteButton deleteButton;
    private HidroSaveButton saveButton;
    
    /** Creates new form MeterPanelView */
    public MeterReadingPanelView() {
        initComponents();
        setMinimumSize(new Dimension(246,61));
        setMaximumSize(new Dimension(246,61));
        setPreferredSize(new Dimension(246,61));
        
        //initTopPanel();*/
    }
    
	protected void initTopPanel() {
		org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(hidrocon.HidroconApp.class).getContext().getResourceMap(HidroconView.class);
		
		saveButton = new HidroSaveButton();
		deleteButton = new HidroDeleteButton();
        		
		deleteButton.setToolTipText(resourceMap.getString("neighbour.details.toolbar.savebutton.tooltip"));
		saveButton.setToolTipText(resourceMap.getString("neighbour.details.toolbar.exitbutton.tooltip"));
        
        //topPanel.addButton(saveButton);
        //topPanel.addButton(deleteButton);
	}
    
    public void writeData(NeighbourMeterView nmv) {
        //topPanel.setTitle("  " + nmv.getMeterTypeName()); 
        //topPanel.setImageIcon(new HidroCustomLegend(nmv.getMeterTypeName(), nmv.getMeterTypeImagePath()));
        serialNumberLabel.setText(nmv.getSerialNumber());
        
        legendPanel.setHexLightColor(nmv.getHexLightColor());
        legendPanel.setHexDarkColor(nmv.getHexDarkColor());
    }
    
    public void readData(NeighbourMeter neighbourMeter) {
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        newMeterReadingTextField = new hidrocon.custom.field.HidroTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        serialNumberLabel = new hidrocon.custom.label.HidroLabel();
        hidroXSLabel1 = new hidrocon.custom.label.HidroXSLabel();
        newMeterReadingTextField1 = new hidrocon.custom.field.HidroTextField();
        hidroXSLabel2 = new hidrocon.custom.label.HidroXSLabel();
        newMeterReadingTextField2 = new hidrocon.custom.field.HidroTextField();
        hidroXSLabel3 = new hidrocon.custom.label.HidroXSLabel();
        legendPanel = new hidrocon.custom.panel.HidroLegendPanel();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout(0, 2));

        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setOpaque(false);
        mainPanel.setLayout(new java.awt.GridBagLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(hidrocon.HidroconApp.class).getContext().getResourceMap(MeterReadingPanelView.class);
        newMeterReadingTextField.setText(resourceMap.getString("newMeterReadingTextField.text")); // NOI18N
        newMeterReadingTextField.setName("newMeterReadingTextField"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 8, 5);
        mainPanel.add(newMeterReadingTextField, gridBagConstraints);

        filler1.setName("filler1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        mainPanel.add(filler1, gridBagConstraints);

        serialNumberLabel.setText(resourceMap.getString("serialNumberLabel.text")); // NOI18N
        serialNumberLabel.setName("serialNumberLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 2, 0, 0);
        mainPanel.add(serialNumberLabel, gridBagConstraints);

        hidroXSLabel1.setText(resourceMap.getString("hidroXSLabel1.text")); // NOI18N
        hidroXSLabel1.setName("hidroXSLabel1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 2, 0, 0);
        mainPanel.add(hidroXSLabel1, gridBagConstraints);

        newMeterReadingTextField1.setName("newMeterReadingTextField1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 8, 5);
        mainPanel.add(newMeterReadingTextField1, gridBagConstraints);

        hidroXSLabel2.setText(resourceMap.getString("hidroXSLabel2.text")); // NOI18N
        hidroXSLabel2.setName("hidroXSLabel2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 2, 0, 0);
        mainPanel.add(hidroXSLabel2, gridBagConstraints);

        newMeterReadingTextField2.setName("newMeterReadingTextField2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 8, 5);
        mainPanel.add(newMeterReadingTextField2, gridBagConstraints);

        hidroXSLabel3.setText(resourceMap.getString("hidroXSLabel3.text")); // NOI18N
        hidroXSLabel3.setName("hidroXSLabel3"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        mainPanel.add(hidroXSLabel3, gridBagConstraints);

        add(mainPanel, java.awt.BorderLayout.CENTER);

        legendPanel.setName("legendPanel"); // NOI18N
        add(legendPanel, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private hidrocon.custom.label.HidroXSLabel hidroXSLabel1;
    private hidrocon.custom.label.HidroXSLabel hidroXSLabel2;
    private hidrocon.custom.label.HidroXSLabel hidroXSLabel3;
    private hidrocon.custom.panel.HidroLegendPanel legendPanel;
    private javax.swing.JPanel mainPanel;
    private hidrocon.custom.field.HidroTextField newMeterReadingTextField;
    private hidrocon.custom.field.HidroTextField newMeterReadingTextField1;
    private hidrocon.custom.field.HidroTextField newMeterReadingTextField2;
    private hidrocon.custom.label.HidroLabel serialNumberLabel;
    // End of variables declaration//GEN-END:variables

    public void setMode(int mode) {
        
    }
    
    public void buttonActionListeners(ActionListener al) {
        //deleteButton.setActionCommand(HidroAction.METER_DELETE);
		//deleteButton.addActionListener(al);
        //saveButton.setActionCommand(HidroAction.METER_SAVE);
		//saveButton.addActionListener(al);
    }  

}
