/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MeterView.java
 *
 * Created on 06-dic-2011, 13:53:35
 */
package hidrocon.component.meter;

import hidrocon.HidroconView;
import hidrocon.core.database.metertype.entities.MeterType;
import hidrocon.core.database.neighbourmeter.entities.NeighbourMeter;
import hidrocon.custom.button.section.HidroDeleteButton;
import hidrocon.custom.button.section.HidroSaveButton;
import hidrocon.custom.panel.HidroItemContentPanel;
import hidrocon.custom.utils.ISelectableElement;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.ActionListener;

/**
 *
 * @author David Sáenz Tagarro
 */
public class MeterTypeNodeView extends HidroItemContentPanel { // implements ISelectableElement {

    private HidroDeleteButton deleteButton;
    private HidroSaveButton saveButton;
    
    /** Creates new form MeterView */
    public MeterTypeNodeView() {
        super();
        initComponents();
        setMinimumSize(new Dimension(269, 29));
        setMaximumSize(new Dimension(269, 29));
        setPreferredSize(new Dimension(269, 29));
        setCursor(new Cursor(Cursor.HAND_CURSOR));
        addMouseListener(this);
    }
    
	protected void initTopPanel() {
		org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(hidrocon.HidroconApp.class).getContext().getResourceMap(HidroconView.class);
		
		saveButton = new HidroSaveButton();
		deleteButton = new HidroDeleteButton();
        		
		deleteButton.setToolTipText(resourceMap.getString("neighbour.details.toolbar.savebutton.tooltip"));
		saveButton.setToolTipText(resourceMap.getString("neighbour.details.toolbar.exitbutton.tooltip"));
	}
    
    public void setData(MeterType meterType) {
        meterTypeNameLabel.setText(meterType.getMeterTypeName());
        legendPanel.setHexLightColor(meterType.getHexLightColor());
        legendPanel.setHexDarkColor(meterType.getHexDarkColor());
    }
    
    public void readData(NeighbourMeter neighbourMeter) {
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        meterTypeNameLabel = new hidrocon.custom.label.HidroLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        legendPanel = new hidrocon.custom.panel.HidroLegendPanel();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout(0, 2));

        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setOpaque(false);
        mainPanel.setLayout(new java.awt.GridBagLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(hidrocon.HidroconApp.class).getContext().getResourceMap(MeterTypeNodeView.class);
        meterTypeNameLabel.setText(resourceMap.getString("meterTypeNameLabel.text")); // NOI18N
        meterTypeNameLabel.setName("meterTypeNameLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        mainPanel.add(meterTypeNameLabel, gridBagConstraints);

        filler1.setName("filler1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        mainPanel.add(filler1, gridBagConstraints);

        add(mainPanel, java.awt.BorderLayout.CENTER);

        legendPanel.setName("legendPanel"); // NOI18N
        add(legendPanel, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private hidrocon.custom.panel.HidroLegendPanel legendPanel;
    private javax.swing.JPanel mainPanel;
    private hidrocon.custom.label.HidroLabel meterTypeNameLabel;
    // End of variables declaration//GEN-END:variables
    
    public void buttonActionListeners(ActionListener al) {
        //deleteButton.setActionCommand(HidroAction.METER_DELETE);
		//deleteButton.addActionListener(al);
        //saveButton.setActionCommand(HidroAction.METER_SAVE);
		//saveButton.addActionListener(al);
    }

}
