/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MeterNodeView.java
 *
 * Created on 06-dic-2011, 13:53:35
 */
package hidrocon.component.meter;

import hidrocon.HidroconView;
import hidrocon.core.database.neighbourmeter.entities.NeighbourMeter;
import hidrocon.core.database.neighbourmeter.entities.NeighbourMeterView;
import hidrocon.custom.button.section.HidroDeleteButton;
import hidrocon.custom.button.section.HidroSaveButton;
import java.awt.Dimension;
import java.awt.event.ActionListener;

/**
 *
 * @author David Sáenz Tagarro
 */
public class MeterNodeView extends javax.swing.JPanel {

    private HidroDeleteButton deleteButton;
    private HidroSaveButton saveButton;
    
    /** Creates new form MeterNodeView */
    public MeterNodeView() {
        initComponents();
        setMinimumSize(new Dimension(231, 93));
        setMaximumSize(new Dimension(231, 93));
        setPreferredSize(new Dimension(231, 93));
        
        //initTopPanel();*/
    }
    
	protected void initTopPanel() {
		org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(hidrocon.HidroconApp.class).getContext().getResourceMap(HidroconView.class);
		
		saveButton = new HidroSaveButton();
		deleteButton = new HidroDeleteButton();
        		
		deleteButton.setToolTipText(resourceMap.getString("neighbour.details.toolbar.savebutton.tooltip"));
		saveButton.setToolTipText(resourceMap.getString("neighbour.details.toolbar.exitbutton.tooltip"));
        
        //topPanel.addButton(saveButton);
        //topPanel.addButton(deleteButton);
	}
    
    public void writeData(NeighbourMeterView nmv) {
        //topPanel.setTitle("  " + nmv.getMeterTypeName()); 
        //topPanel.setImageIcon(new HidroCustomLegend(nmv.getMeterTypeName(), nmv.getMeterTypeImagePath()));
        serialNumberField.setText(nmv.getSerialNumber());
        
        legendPanel.setHexLightColor(nmv.getHexLightColor());
        legendPanel.setHexDarkColor(nmv.getHexDarkColor());
    }
    
    public void readData(NeighbourMeter neighbourMeter) {
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new hidrocon.custom.panel.HidroItemContentPanel();
        jPanel1 = new javax.swing.JPanel();
        newMeterReadingTextField = new hidrocon.custom.field.HidroTextField();
        newReadingLabel = new hidrocon.custom.label.HidroLabel();
        lastMeterReadingDateField = new hidrocon.custom.field.HidroTextField();
        serialNumberLabel = new hidrocon.custom.label.HidroLabel();
        lastReadingLabel = new hidrocon.custom.label.HidroLabel();
        serialNumberField = new hidrocon.custom.field.HidroTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        legendPanel = new hidrocon.custom.panel.HidroLegendPanel();

        setName("Form"); // NOI18N
        setOpaque(false);
        setLayout(new java.awt.BorderLayout(0, 2));

        mainPanel.setBorder(null);
        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        newMeterReadingTextField.setName("newMeterReadingTextField"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 10, 0);
        jPanel1.add(newMeterReadingTextField, gridBagConstraints);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(hidrocon.HidroconApp.class).getContext().getResourceMap(MeterNodeView.class);
        newReadingLabel.setText(resourceMap.getString("newReadingLabel.text")); // NOI18N
        newReadingLabel.setName("newReadingLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(newReadingLabel, gridBagConstraints);

        lastMeterReadingDateField.setName("lastMeterReadingDateField"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel1.add(lastMeterReadingDateField, gridBagConstraints);

        serialNumberLabel.setText(resourceMap.getString("serialNumberLabel.text")); // NOI18N
        serialNumberLabel.setName("serialNumberLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(serialNumberLabel, gridBagConstraints);

        lastReadingLabel.setText(resourceMap.getString("lastReadingLabel.text")); // NOI18N
        lastReadingLabel.setName("lastReadingLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(lastReadingLabel, gridBagConstraints);

        serialNumberField.setName("serialNumberField"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 125;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanel1.add(serialNumberField, gridBagConstraints);

        filler1.setName("filler1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(filler1, gridBagConstraints);

        mainPanel.add(jPanel1, java.awt.BorderLayout.CENTER);

        legendPanel.setName("legendPanel"); // NOI18N
        mainPanel.add(legendPanel, java.awt.BorderLayout.WEST);

        add(mainPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel jPanel1;
    private hidrocon.custom.field.HidroTextField lastMeterReadingDateField;
    private hidrocon.custom.label.HidroLabel lastReadingLabel;
    private hidrocon.custom.panel.HidroLegendPanel legendPanel;
    private hidrocon.custom.panel.HidroItemContentPanel mainPanel;
    private hidrocon.custom.field.HidroTextField newMeterReadingTextField;
    private hidrocon.custom.label.HidroLabel newReadingLabel;
    private hidrocon.custom.field.HidroTextField serialNumberField;
    private hidrocon.custom.label.HidroLabel serialNumberLabel;
    // End of variables declaration//GEN-END:variables

    public void setMode(int mode) {
        
    }
    
    public void buttonActionListeners(ActionListener al) {
        //deleteButton.setActionCommand(HidroAction.METER_DELETE);
		//deleteButton.addActionListener(al);
        //saveButton.setActionCommand(HidroAction.METER_SAVE);
		//saveButton.addActionListener(al);
    }  

}
