/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MeterCreationPanelDialog.java
 *
 * Created on 29-nov-2011, 7:16:41
 */
package hidrocon.ui.meter.dialog;

import hidrocon.custom.dialog.HidroDialog;
import hidrocon.ui.meter.creation.MeterCreationPanelController;
import hidrocon.ui.meter.creation.MeterCreationPanelModel;
import hidrocon.ui.meter.creation.MeterCreationPanelView;
import java.awt.Dimension;

/**
 *
 * @author David Sáenz Tagarro
 */
public class MeterCreationDialog extends HidroDialog {

    private MeterCreationPanelModel model;    
    private MeterCreationPanelView view;
    private MeterCreationPanelController controller;

    /** Creates new form MeterCreationPanelDialog */
    public MeterCreationDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initContent();
    }
    
    private void initContent() {
        view = new MeterCreationPanelView();
        model = new MeterCreationPanelModel();
        controller = new MeterCreationPanelController(model, view);
        
        controller.setDialog(this);
        view.setMinimumSize(new Dimension(600,246));
        view.setMaximumSize(new Dimension(600,246));
        view.setPreferredSize(new Dimension(600,246));
        getContentPane().add(view);
        
        //HidroBlockingLayerUI layerUI = new HidroBlockingLayerUI();
        //JLayer<JPanel> jlayerMain = new JLayer<JPanel>(view, layerUI);
        //getContentPane().add(jlayerMain);
        
        pack();        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
