/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RouteDateDetailsView.java
 *
 * Created on 25-nov-2011, 22:16:43
 */
package hidrocon.ui.route.date;

import hidrocon.HidroconView;
import hidrocon.core.database.routedate.entities.RouteDate;
import hidrocon.core.utils.ActionKey;
import hidrocon.custom.button.toolbar.HidroDeleteButton;
import hidrocon.custom.button.toolbar.HidroInfoButton;
import hidrocon.custom.button.toolbar.HidroNewButton;
import hidrocon.custom.panel.HidroMainPanel;
import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.awt.event.MouseListener;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author David Sáenz Tagarro
 */
public class RouteDatePanelView extends HidroMainPanel {
    
    private int mode;
    
    HidroNewButton calendarNewButton;
    HidroInfoButton updateRouteDateButton;    
    HidroDeleteButton calendarDeleteButton;
    
    /** Creates new form RouteDateDetailsView */
    public RouteDatePanelView() {
        initComponents();
        initTopPanel();
        customizeComponents(); 
    }
    
	private void initTopPanel() {
		org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(hidrocon.HidroconApp.class).getContext().getResourceMap(HidroconView.class);
		topPanel.setTitle("  " + resourceMap.getString("routedate.toppanel.title"));

        calendarNewButton = new HidroNewButton();
        updateRouteDateButton = new HidroInfoButton();
        calendarDeleteButton = new HidroDeleteButton();
        
        calendarNewButton.setToolTipText(resourceMap.getString("routedates.toolbar.newbutton.tooltip"));
		calendarDeleteButton.setToolTipText(resourceMap.getString("routedates.toolbar.deletebutton.tooltip"));
        
        topPanel.addButton(calendarNewButton);
        topPanel.addButton(updateRouteDateButton);
        topPanel.addButton(calendarDeleteButton);
	}

    private void customizeComponents() {
        routeDateTable.setRowSorter(null);
        routeDateTable.setAutoCreateRowSorter(false);
    }

    public int getRouteDateSelectedIndex() {
        if (routeDateTable.getSelectedRow()>-1) {
            return routeDateTable.convertRowIndexToModel(routeDateTable.getSelectedRow());
        }
        return -1;
    }
    
    public void selectRouteDateTableRow(int index) {
        routeDateTable.setRowSelectionInterval(index, index);
    }
    
    public RouteDate getRouteDateSelected() {
		if (routeDateTable.getSelectedRow() > -1) {
			return routeDateList.get(routeDateTable.convertRowIndexToModel(routeDateTable.getSelectedRow()));
        }
        return null;
    }
    
    public JPanel getMainPanel() {
        return mainPanel;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        routeDateList = org.jdesktop.observablecollections.ObservableCollections.observableList(new ArrayList());
        topPanel = new hidrocon.custom.panel.HidroTopPanel();
        mainPanel = new hidrocon.custom.panel.HidroMainPanel();
        routeDateScrollPane = new javax.swing.JScrollPane();
        routeDateTable = new hidrocon.custom.table.HidroTable();
        leftFiller = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 32767));
        rightFiller = new javax.swing.Box.Filler(new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 0), new java.awt.Dimension(25, 32767));
        bottomFiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25), new java.awt.Dimension(32767, 25));
        topFiller = new javax.swing.Box.Filler(new java.awt.Dimension(0, 25), new java.awt.Dimension(0, 25), new java.awt.Dimension(32767, 25));

        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(650, 350));
        setLayout(new java.awt.BorderLayout());

        topPanel.setName("topPanel"); // NOI18N
        add(topPanel, java.awt.BorderLayout.PAGE_START);

        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setLayout(new java.awt.GridBagLayout());

        routeDateScrollPane.setName("routeDateScrollPane"); // NOI18N

        routeDateTable.setName("routeDateTable"); // NOI18N

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${routeDateList}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, routeDateTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${readingDate}"));
        columnBinding.setColumnName("Reading Date");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${statusId}"));
        columnBinding.setColumnName("Status Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        routeDateScrollPane.setViewportView(routeDateTable);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(hidrocon.HidroconApp.class).getContext().getResourceMap(RouteDatePanelView.class);
        routeDateTable.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("routeDateTable.columnModel.title0")); // NOI18N
        routeDateTable.getColumnModel().getColumn(1).setMinWidth(80);
        routeDateTable.getColumnModel().getColumn(1).setMaxWidth(80);
        routeDateTable.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("routeDateTable.columnModel.title1")); // NOI18N

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        mainPanel.add(routeDateScrollPane, gridBagConstraints);

        leftFiller.setName("leftFiller"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        mainPanel.add(leftFiller, gridBagConstraints);

        rightFiller.setName("rightFiller"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        mainPanel.add(rightFiller, gridBagConstraints);

        bottomFiller.setName("bottomFiller"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        mainPanel.add(bottomFiller, gridBagConstraints);

        topFiller.setName("topFiller"); // NOI18N
        mainPanel.add(topFiller, new java.awt.GridBagConstraints());

        add(mainPanel, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler bottomFiller;
    private javax.swing.Box.Filler leftFiller;
    private hidrocon.custom.panel.HidroMainPanel mainPanel;
    private javax.swing.Box.Filler rightFiller;
    private java.util.List<RouteDate> routeDateList;
    private javax.swing.JScrollPane routeDateScrollPane;
    private hidrocon.custom.table.HidroTable routeDateTable;
    private javax.swing.Box.Filler topFiller;
    private hidrocon.custom.panel.HidroTopPanel topPanel;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    
	protected PropertyChangeSupport propertyChangeSupport = new PropertyChangeSupport(this);

    @Override
	public void addPropertyChangeListener(PropertyChangeListener l) {
		propertyChangeSupport.addPropertyChangeListener(l);
	}

    @Override
	public void removePropertyChangeListener(PropertyChangeListener l) {
		propertyChangeSupport.removePropertyChangeListener(l);
	}  
    
    /**
     * @return the routedatesList
     */
    public java.util.List<RouteDate> getRouteDateList() {
        return routeDateList;
    }

    /**
     * @param routedatesList the routedatesList to set
     */
    public void setRouteDateList(java.util.List<RouteDate> routedatesList) {
        java.util.List<RouteDate> oldRecord = this.routeDateList;
        this.routeDateList = routedatesList;
        propertyChangeSupport.firePropertyChange("routeDateList", oldRecord, routeDateList);          
    }
    
    public void buttonActionListeners(ActionListener al) {
        updateRouteDateButton.setActionCommand(ActionKey.ROUTE_DATE_UPDATE);
        updateRouteDateButton.addActionListener(al);
        calendarNewButton.setActionCommand(ActionKey.ROUTE_DATE_CREATE);
		calendarNewButton.addActionListener(al);        
        calendarDeleteButton.setActionCommand(ActionKey.ROUTE_DATE_DELETE);
		calendarDeleteButton.addActionListener(al);            
    }
    
    public void tableKeyListeners(KeyListener kl) {
        routeDateTable.addKeyListener(kl);
    }
    
    public void tableMouseListeners(MouseListener ml) {
        routeDateTable.addMouseListener(ml);
    }
    
    
}
