/*
 * HidroconView.java
 */

package hidrocon;

import hidrocon.core.generic.EntityManagerProvider;
import hidrocon.core.utils.ActionKey;
import java.awt.event.ActionListener;
import javax.swing.JComponent;
import org.jdesktop.application.Action;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import javax.swing.JDialog;
import javax.swing.JFrame;


/**
 * The application's main frame.
 */
public class HidroconView extends FrameView {
    
    public HidroconView(SingleFrameApplication app) {
        super(app);

        initComponents();
        initFocus();
        //Create unique EntityManagerFactory (slow process)
        EntityManagerProvider.getEntityManagerProvider().getEntityManagerFactory();
    }
        
    private void initFocus() {
        dataBaseMenu.requestFocusInWindow();
    }
        
    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = HidroconApp.getApplication().getMainFrame();
            aboutBox = new HidroconAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        HidroconApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new hidrocon.custom.menu.HidroMenuBar();
        dataBaseMenu = new hidrocon.custom.menu.HidroMenuHeader();
        routeMenu = new hidrocon.custom.menu.HidroMenuItem();
        buildingMenu = new hidrocon.custom.menu.HidroMenuItem();
        commentMenu = new hidrocon.custom.menu.HidroMenuItem();
        administratorMenu = new hidrocon.custom.menu.HidroMenuItem();
        rateMenu = new hidrocon.custom.menu.HidroMenuItem();
        configurationMenu = new hidrocon.custom.menu.HidroMenu();
        systemMenu = new hidrocon.custom.menu.HidroMenuItem();
        locationMenu = new hidrocon.custom.menu.HidroMenuItem();
        migrationMenu = new hidrocon.custom.menu.HidroMenuItem();
        invoiceMenu = new hidrocon.custom.menu.HidroMenuHeader();
        meterReadingMenu = new hidrocon.custom.menu.HidroMenuItem();
        jMenuItem2 = new hidrocon.custom.menu.HidroMenuItem();
        jMenuItem9 = new hidrocon.custom.menu.HidroMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new hidrocon.custom.menu.HidroMenuItem();
        jMenuItem4 = new hidrocon.custom.menu.HidroMenuItem();
        jMenuItem5 = new hidrocon.custom.menu.HidroMenuItem();
        jMenuItem6 = new hidrocon.custom.menu.HidroMenuItem();
        inicializvariosMenu = new hidrocon.custom.menu.HidroMenuHeader();
        jMenuItem7 = new hidrocon.custom.menu.HidroMenuItem();
        jMenuItem8 = new hidrocon.custom.menu.HidroMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem10 = new hidrocon.custom.menu.HidroMenuItem();
        jMenuItem11 = new hidrocon.custom.menu.HidroMenuItem();
        jMenuItem12 = new hidrocon.custom.menu.HidroMenuItem();
        jMenuItem13 = new hidrocon.custom.menu.HidroMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem14 = new hidrocon.custom.menu.HidroMenuItem();
        jMenuItem15 = new hidrocon.custom.menu.HidroMenuItem();
        jMenuItem16 = new hidrocon.custom.menu.HidroMenuItem();
        jMenuItem17 = new hidrocon.custom.menu.HidroMenuItem();
        jMenuItem18 = new hidrocon.custom.menu.HidroMenuItem();
        jMenuItem19 = new hidrocon.custom.menu.HidroMenuItem();
        controlMenu = new hidrocon.custom.menu.HidroMenuHeader();
        jMenuItem20 = new hidrocon.custom.menu.HidroMenuItem();
        jMenuItem21 = new hidrocon.custom.menu.HidroMenuItem();
        empresaMenu = new hidrocon.custom.menu.HidroMenuHeader();
        jMenuItem22 = new hidrocon.custom.menu.HidroMenuItem();
        jMenuItem23 = new hidrocon.custom.menu.HidroMenuItem();
        jMenuItem24 = new hidrocon.custom.menu.HidroMenuItem();
        jMenuItem25 = new hidrocon.custom.menu.HidroMenuItem();
        jMenuItem30 = new hidrocon.custom.menu.HidroMenuItem();
        jMenuItem26 = new hidrocon.custom.menu.HidroMenuItem();
        jMenuItem27 = new hidrocon.custom.menu.HidroMenuItem();
        jMenuItem28 = new hidrocon.custom.menu.HidroMenuItem();
        jMenuItem29 = new hidrocon.custom.menu.HidroMenuItem();
        hidrocon.custom.menu.HidroMenuHeader ayudaMenu = new hidrocon.custom.menu.HidroMenuHeader();
        hidrocon.custom.menu.HidroMenuItem aboutMenuItem = new hidrocon.custom.menu.HidroMenuItem();
        hidrocon.custom.menu.HidroMenuHeader fileMenu = new hidrocon.custom.menu.HidroMenuHeader();
        hidrocon.custom.menu.HidroMenuItem newRecordMenuItem = new hidrocon.custom.menu.HidroMenuItem();
        hidrocon.custom.menu.HidroMenuItem deleteRecordMenuItem = new hidrocon.custom.menu.HidroMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        hidrocon.custom.menu.HidroMenuItem saveMenuItem = new hidrocon.custom.menu.HidroMenuItem();
        hidrocon.custom.menu.HidroMenuItem refreshMenuItem = new hidrocon.custom.menu.HidroMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        hidrocon.custom.menu.HidroMenuItem exitMenuItem = new hidrocon.custom.menu.HidroMenuItem();
        blankPanel = new hidrocon.custom.panel.HidroMainPanel();

        menuBar.setName("menuBar"); // NOI18N

        dataBaseMenu.setMnemonic('B');
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(hidrocon.HidroconApp.class).getContext().getResourceMap(HidroconView.class);
        dataBaseMenu.setText(resourceMap.getString("dataBaseMenu.text")); // NOI18N
        dataBaseMenu.setName("dataBaseMenu"); // NOI18N

        routeMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        routeMenu.setIcon(resourceMap.getIcon("routeMenu.icon")); // NOI18N
        routeMenu.setText(resourceMap.getString("routeMenu.text")); // NOI18N
        routeMenu.setName("routeMenu"); // NOI18N
        dataBaseMenu.add(routeMenu);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(hidrocon.HidroconApp.class).getContext().getActionMap(HidroconView.class, this);
        buildingMenu.setAction(actionMap.get("showBuildingsByNumfinca")); // NOI18N
        buildingMenu.setIcon(resourceMap.getIcon("buildingMenu.icon")); // NOI18N
        buildingMenu.setText(resourceMap.getString("buildingMenu.text")); // NOI18N
        buildingMenu.setName("buildingMenu"); // NOI18N
        dataBaseMenu.add(buildingMenu);

        commentMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        commentMenu.setIcon(resourceMap.getIcon("commentMenu.icon")); // NOI18N
        commentMenu.setText(resourceMap.getString("commentMenu.text")); // NOI18N
        commentMenu.setName("commentMenu"); // NOI18N
        dataBaseMenu.add(commentMenu);

        administratorMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        administratorMenu.setIcon(resourceMap.getIcon("administratorMenu.icon")); // NOI18N
        administratorMenu.setText(resourceMap.getString("administratorMenu.text")); // NOI18N
        administratorMenu.setName("administratorMenu"); // NOI18N
        dataBaseMenu.add(administratorMenu);

        rateMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        rateMenu.setIcon(resourceMap.getIcon("rateMenu.icon")); // NOI18N
        rateMenu.setText(resourceMap.getString("rateMenu.text")); // NOI18N
        rateMenu.setName("rateMenu"); // NOI18N
        dataBaseMenu.add(rateMenu);

        configurationMenu.setIcon(resourceMap.getIcon("configurationMenu.icon")); // NOI18N
        configurationMenu.setText(resourceMap.getString("configurationMenu.text")); // NOI18N
        configurationMenu.setName("configurationMenu"); // NOI18N

        systemMenu.setText(resourceMap.getString("systemMenu.text")); // NOI18N
        systemMenu.setName("systemMenu"); // NOI18N
        configurationMenu.add(systemMenu);

        locationMenu.setText(resourceMap.getString("locationMenu.text")); // NOI18N
        locationMenu.setName("locationMenu"); // NOI18N
        configurationMenu.add(locationMenu);

        migrationMenu.setText(resourceMap.getString("migrationMenu.text")); // NOI18N
        migrationMenu.setName("migrationMenu"); // NOI18N
        configurationMenu.add(migrationMenu);

        dataBaseMenu.add(configurationMenu);

        menuBar.add(dataBaseMenu);

        invoiceMenu.setMnemonic('F');
        invoiceMenu.setText(resourceMap.getString("invoiceMenu.text")); // NOI18N
        invoiceMenu.setName("invoiceMenu"); // NOI18N

        meterReadingMenu.setText(resourceMap.getString("meterReadingMenu.text")); // NOI18N
        meterReadingMenu.setName("meterReadingMenu"); // NOI18N
        invoiceMenu.add(meterReadingMenu);

        jMenuItem2.setText(resourceMap.getString("jMenuItem2.text")); // NOI18N
        jMenuItem2.setName("jMenuItem2"); // NOI18N
        invoiceMenu.add(jMenuItem2);

        jMenuItem9.setText(resourceMap.getString("jMenuItem9.text")); // NOI18N
        jMenuItem9.setName("jMenuItem9"); // NOI18N
        invoiceMenu.add(jMenuItem9);

        jSeparator4.setName("jSeparator4"); // NOI18N
        invoiceMenu.add(jSeparator4);

        jMenuItem3.setText(resourceMap.getString("jMenuItem3.text")); // NOI18N
        jMenuItem3.setName("jMenuItem3"); // NOI18N
        invoiceMenu.add(jMenuItem3);

        jMenuItem4.setText(resourceMap.getString("jMenuItem4.text")); // NOI18N
        jMenuItem4.setName("jMenuItem4"); // NOI18N
        invoiceMenu.add(jMenuItem4);

        jMenuItem5.setText(resourceMap.getString("jMenuItem5.text")); // NOI18N
        jMenuItem5.setName("jMenuItem5"); // NOI18N
        invoiceMenu.add(jMenuItem5);

        jMenuItem6.setText(resourceMap.getString("jMenuItem6.text")); // NOI18N
        jMenuItem6.setName("jMenuItem6"); // NOI18N
        invoiceMenu.add(jMenuItem6);

        menuBar.add(invoiceMenu);

        inicializvariosMenu.setMnemonic('I');
        inicializvariosMenu.setText(resourceMap.getString("inicializvariosMenu.text")); // NOI18N
        inicializvariosMenu.setName("inicializvariosMenu"); // NOI18N

        jMenuItem7.setText(resourceMap.getString("jMenuItem7.text")); // NOI18N
        jMenuItem7.setName("jMenuItem7"); // NOI18N
        inicializvariosMenu.add(jMenuItem7);

        jMenuItem8.setText(resourceMap.getString("jMenuItem8.text")); // NOI18N
        jMenuItem8.setName("jMenuItem8"); // NOI18N
        inicializvariosMenu.add(jMenuItem8);

        jSeparator5.setName("jSeparator5"); // NOI18N
        inicializvariosMenu.add(jSeparator5);

        jMenuItem10.setText(resourceMap.getString("jMenuItem10.text")); // NOI18N
        jMenuItem10.setName("jMenuItem10"); // NOI18N
        inicializvariosMenu.add(jMenuItem10);

        jMenuItem11.setText(resourceMap.getString("jMenuItem11.text")); // NOI18N
        jMenuItem11.setName("jMenuItem11"); // NOI18N
        inicializvariosMenu.add(jMenuItem11);

        jMenuItem12.setText(resourceMap.getString("jMenuItem12.text")); // NOI18N
        jMenuItem12.setName("jMenuItem12"); // NOI18N
        inicializvariosMenu.add(jMenuItem12);

        jMenuItem13.setText(resourceMap.getString("jMenuItem13.text")); // NOI18N
        jMenuItem13.setName("jMenuItem13"); // NOI18N
        inicializvariosMenu.add(jMenuItem13);

        jSeparator6.setName("jSeparator6"); // NOI18N
        inicializvariosMenu.add(jSeparator6);

        jMenuItem14.setText(resourceMap.getString("jMenuItem14.text")); // NOI18N
        jMenuItem14.setName("jMenuItem14"); // NOI18N
        inicializvariosMenu.add(jMenuItem14);

        jMenuItem15.setText(resourceMap.getString("jMenuItem15.text")); // NOI18N
        jMenuItem15.setName("jMenuItem15"); // NOI18N
        inicializvariosMenu.add(jMenuItem15);

        jMenuItem16.setText(resourceMap.getString("jMenuItem16.text")); // NOI18N
        jMenuItem16.setName("jMenuItem16"); // NOI18N
        inicializvariosMenu.add(jMenuItem16);

        jMenuItem17.setText(resourceMap.getString("jMenuItem17.text")); // NOI18N
        jMenuItem17.setName("jMenuItem17"); // NOI18N
        inicializvariosMenu.add(jMenuItem17);

        jMenuItem18.setText(resourceMap.getString("jMenuItem18.text")); // NOI18N
        jMenuItem18.setName("jMenuItem18"); // NOI18N
        inicializvariosMenu.add(jMenuItem18);

        jMenuItem19.setText(resourceMap.getString("jMenuItem19.text")); // NOI18N
        jMenuItem19.setName("jMenuItem19"); // NOI18N
        inicializvariosMenu.add(jMenuItem19);

        menuBar.add(inicializvariosMenu);

        controlMenu.setText(resourceMap.getString("controlMenu.text")); // NOI18N
        controlMenu.setName("controlMenu"); // NOI18N

        jMenuItem20.setText(resourceMap.getString("jMenuItem20.text")); // NOI18N
        jMenuItem20.setName("jMenuItem20"); // NOI18N
        controlMenu.add(jMenuItem20);

        jMenuItem21.setText(resourceMap.getString("jMenuItem21.text")); // NOI18N
        jMenuItem21.setName("jMenuItem21"); // NOI18N
        controlMenu.add(jMenuItem21);

        menuBar.add(controlMenu);

        empresaMenu.setText(resourceMap.getString("empresaMenu.text")); // NOI18N
        empresaMenu.setName("empresaMenu"); // NOI18N

        jMenuItem22.setText(resourceMap.getString("jMenuItem22.text")); // NOI18N
        jMenuItem22.setName("jMenuItem22"); // NOI18N
        empresaMenu.add(jMenuItem22);

        jMenuItem23.setText(resourceMap.getString("jMenuItem23.text")); // NOI18N
        jMenuItem23.setName("jMenuItem23"); // NOI18N
        empresaMenu.add(jMenuItem23);

        jMenuItem24.setText(resourceMap.getString("jMenuItem24.text")); // NOI18N
        jMenuItem24.setName("jMenuItem24"); // NOI18N
        empresaMenu.add(jMenuItem24);

        jMenuItem25.setText(resourceMap.getString("jMenuItem25.text")); // NOI18N
        jMenuItem25.setName("jMenuItem25"); // NOI18N
        empresaMenu.add(jMenuItem25);

        jMenuItem30.setText(resourceMap.getString("jMenuItem30.text")); // NOI18N
        jMenuItem30.setName("jMenuItem30"); // NOI18N
        empresaMenu.add(jMenuItem30);

        jMenuItem26.setText(resourceMap.getString("jMenuItem26.text")); // NOI18N
        jMenuItem26.setName("jMenuItem26"); // NOI18N
        empresaMenu.add(jMenuItem26);

        jMenuItem27.setText(resourceMap.getString("jMenuItem27.text")); // NOI18N
        jMenuItem27.setName("jMenuItem27"); // NOI18N
        empresaMenu.add(jMenuItem27);

        jMenuItem28.setText(resourceMap.getString("jMenuItem28.text")); // NOI18N
        jMenuItem28.setName("jMenuItem28"); // NOI18N
        empresaMenu.add(jMenuItem28);

        jMenuItem29.setText(resourceMap.getString("jMenuItem29.text")); // NOI18N
        jMenuItem29.setName("jMenuItem29"); // NOI18N
        empresaMenu.add(jMenuItem29);

        menuBar.add(empresaMenu);

        ayudaMenu.setText(resourceMap.getString("ayudaMenu.text")); // NOI18N
        ayudaMenu.setName("ayudaMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setText(resourceMap.getString("aboutMenuItem.text")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        ayudaMenu.add(aboutMenuItem);

        menuBar.add(ayudaMenu);

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        newRecordMenuItem.setAction(actionMap.get("newRecord")); // NOI18N
        newRecordMenuItem.setName("newRecordMenuItem"); // NOI18N
        fileMenu.add(newRecordMenuItem);

        deleteRecordMenuItem.setAction(actionMap.get("deleteRecord")); // NOI18N
        deleteRecordMenuItem.setName("deleteRecordMenuItem"); // NOI18N
        fileMenu.add(deleteRecordMenuItem);

        jSeparator1.setName("jSeparator1"); // NOI18N
        fileMenu.add(jSeparator1);

        saveMenuItem.setAction(actionMap.get("save")); // NOI18N
        saveMenuItem.setName("saveMenuItem"); // NOI18N
        fileMenu.add(saveMenuItem);

        refreshMenuItem.setAction(actionMap.get("refresh")); // NOI18N
        refreshMenuItem.setName("refreshMenuItem"); // NOI18N
        fileMenu.add(refreshMenuItem);

        jSeparator2.setName("jSeparator2"); // NOI18N
        fileMenu.add(jSeparator2);

        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        blankPanel.setName("blankPanel"); // NOI18N

        javax.swing.GroupLayout blankPanelLayout = new javax.swing.GroupLayout(blankPanel);
        blankPanel.setLayout(blankPanelLayout);
        blankPanelLayout.setHorizontalGroup(
            blankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        blankPanelLayout.setVerticalGroup(
            blankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );

        setComponent(blankPanel);
        setMenuBar(menuBar);
    }// </editor-fold>//GEN-END:initComponents

    public void setComponentObj(JComponent component) {
		this.setComponent(component);
		this.getFrame().pack();
        this.getComponent().transferFocus();        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private hidrocon.custom.menu.HidroMenuItem administratorMenu;
    private hidrocon.custom.panel.HidroMainPanel blankPanel;
    private hidrocon.custom.menu.HidroMenuItem buildingMenu;
    private hidrocon.custom.menu.HidroMenuItem commentMenu;
    private hidrocon.custom.menu.HidroMenu configurationMenu;
    private hidrocon.custom.menu.HidroMenuHeader controlMenu;
    private hidrocon.custom.menu.HidroMenuHeader dataBaseMenu;
    private hidrocon.custom.menu.HidroMenuHeader empresaMenu;
    private hidrocon.custom.menu.HidroMenuHeader inicializvariosMenu;
    private hidrocon.custom.menu.HidroMenuHeader invoiceMenu;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem10;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem11;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem12;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem13;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem14;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem15;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem16;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem17;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem18;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem19;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem2;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem20;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem21;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem22;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem23;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem24;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem25;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem26;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem27;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem28;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem29;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem3;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem30;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem4;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem5;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem6;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem7;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem8;
    private hidrocon.custom.menu.HidroMenuItem jMenuItem9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private hidrocon.custom.menu.HidroMenuItem locationMenu;
    private hidrocon.custom.menu.HidroMenuBar menuBar;
    private hidrocon.custom.menu.HidroMenuItem meterReadingMenu;
    private hidrocon.custom.menu.HidroMenuItem migrationMenu;
    private hidrocon.custom.menu.HidroMenuItem rateMenu;
    private hidrocon.custom.menu.HidroMenuItem routeMenu;
    private hidrocon.custom.menu.HidroMenuItem systemMenu;
    // End of variables declaration//GEN-END:variables

    private JDialog aboutBox;
    
    public void initMenuAction(ActionListener al) {
        migrationMenu.setActionCommand(ActionKey.MENU_MIGRATION);
        migrationMenu.addActionListener(al);
        administratorMenu.setActionCommand(ActionKey.MENU_ADMINISTRATOR);
        administratorMenu.addActionListener(al);
        buildingMenu.setActionCommand(ActionKey.MENU_BUILDING);
        buildingMenu.addActionListener(al);        
        routeMenu.setActionCommand(ActionKey.MENU_ROUTE);
        routeMenu.addActionListener(al);                
        commentMenu.setActionCommand(ActionKey.MENU_COMMENT);
        commentMenu.addActionListener(al);
        rateMenu.setActionCommand(ActionKey.MENU_RATE);
        rateMenu.addActionListener(al);
        
        meterReadingMenu.setActionCommand(ActionKey.MENU_METERREADING);
        meterReadingMenu.addActionListener(al);
    }
}
