/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MeterPanelView.java
 *
 * Created on 06-dic-2011, 13:53:35
 */
package hidrocon.component.neighbour;

import hidrocon.HidroconView;
import hidrocon.core.database.neighbour.entities.Neighbour;
import hidrocon.core.database.neighbourmeter.entities.NeighbourMeter;
import hidrocon.custom.button.section.HidroDeleteButton;
import hidrocon.custom.button.section.HidroSaveButton;
import hidrocon.custom.panel.HidroItemContentPanel;
import java.awt.Dimension;
import java.awt.event.ActionListener;

/**
 *
 * @author David Sáenz Tagarro
 */
public class NeighbourPanelView extends HidroItemContentPanel {

    private HidroDeleteButton deleteButton;
    private HidroSaveButton saveButton;
    
    /** Creates new form MeterPanelView */
    public NeighbourPanelView() {
        initComponents();
        setMinimumSize(new Dimension(175, 61));
        setMaximumSize(new Dimension(175, 61));
        setPreferredSize(new Dimension(175, 61));
        
        //initTopPanel();*/
    }
    
	protected void initTopPanel() {
		org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(hidrocon.HidroconApp.class).getContext().getResourceMap(HidroconView.class);
		
		saveButton = new HidroSaveButton();
		deleteButton = new HidroDeleteButton();
        		
		deleteButton.setToolTipText(resourceMap.getString("neighbour.details.toolbar.savebutton.tooltip"));
		saveButton.setToolTipText(resourceMap.getString("neighbour.details.toolbar.exitbutton.tooltip"));
        
        //topPanel.addButton(saveButton);
        //topPanel.addButton(deleteButton);
	}
    
    public void writeData(Neighbour neighbour) {
        floorLabel.setText(neighbour.getFloor());
        neighbourNumberLabel.setText(neighbour.getNeighbourNumber().toString());
        neighbourNameLabel.setText("<html>"+neighbour.getNeighbourName()+"</html>");
    }
    
    public void readData(NeighbourMeter neighbourMeter) {
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        neighbourNumberLabel = new hidrocon.custom.label.HidroLabel();
        floorLabel = new hidrocon.custom.label.HidroLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        neighbourNameLabel = new hidrocon.custom.label.HidroXSLabel();
        legendPanel = new hidrocon.custom.panel.HidroLegendPanel();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout(0, 2));

        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setOpaque(false);
        mainPanel.setLayout(new java.awt.GridBagLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(hidrocon.HidroconApp.class).getContext().getResourceMap(NeighbourPanelView.class);
        neighbourNumberLabel.setText(resourceMap.getString("neighbourNumberLabel.text")); // NOI18N
        neighbourNumberLabel.setName("neighbourNumberLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 0);
        mainPanel.add(neighbourNumberLabel, gridBagConstraints);

        floorLabel.setText(resourceMap.getString("floorLabel.text")); // NOI18N
        floorLabel.setName("floorLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        mainPanel.add(floorLabel, gridBagConstraints);

        filler1.setName("filler1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        mainPanel.add(filler1, gridBagConstraints);

        neighbourNameLabel.setText(resourceMap.getString("neighbourNameLabel.text")); // NOI18N
        neighbourNameLabel.setName("neighbourNameLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        mainPanel.add(neighbourNameLabel, gridBagConstraints);

        add(mainPanel, java.awt.BorderLayout.CENTER);

        legendPanel.setBackground(resourceMap.getColor("legendPanel.background")); // NOI18N
        legendPanel.setForeground(resourceMap.getColor("legendPanel.foreground")); // NOI18N
        legendPanel.setName("legendPanel"); // NOI18N
        add(legendPanel, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private hidrocon.custom.label.HidroLabel floorLabel;
    private hidrocon.custom.panel.HidroLegendPanel legendPanel;
    private javax.swing.JPanel mainPanel;
    private hidrocon.custom.label.HidroXSLabel neighbourNameLabel;
    private hidrocon.custom.label.HidroLabel neighbourNumberLabel;
    // End of variables declaration//GEN-END:variables

    public void setMode(int mode) {
        
    }
    
    public void buttonActionListeners(ActionListener al) {
        //deleteButton.setActionCommand(HidroAction.METER_DELETE);
		//deleteButton.addActionListener(al);
        //saveButton.setActionCommand(HidroAction.METER_SAVE);
		//saveButton.addActionListener(al);
    }  

}
