/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DateDetailsDialog.java
 *
 * Created on 09-oct-2011, 5:37:44
 */

package hidrocon.ui.route.dialog;

import hidrocon.HidroconApp;
import hidrocon.HidroconView;
import hidrocon.custom.button.toolbar.HidroExitButton;
import hidrocon.custom.button.toolbar.HidroSaveButton;
import hidrocon.custom.dialog.HidroDialog;
import hidrocon.custom.dialog.calendar.HidroCalendarDialog;
import hidrocon.custom.dialog.interfaces.ISelector;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.AbstractAction;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;

/**
 *
 * @author david
 */
public final class DateSelectionDialog extends HidroDialog implements ISelector {

	private boolean dateSaved = false;
    
	private HidroCalendarDialog calendarDialog;
    
    /** Creates new form BuildingDetailsDialog */
    public DateSelectionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        
        initComponents();
		initTopPanel();
        initKeyBinding();
        
        calendarButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
                if (calendarDialog == null) {
                    JFrame mainFrame = HidroconApp.getApplication().getMainFrame();
                    calendarDialog = new HidroCalendarDialog(mainFrame,true);
                    calendarDialog.setLocationRelativeTo(mainFrame);
                    
                    //calendarDialog.getDateSelected()
                }
                calendarDialog.centerParent();
                HidroconApp.getApplication().show(calendarDialog);
                
                java.util.Date dateSelected = calendarDialog.getDateSelected();
                
                dateField.setValue(dateSelected);
			}
		});
    }

	/*
	 * HidroDialog abstract methods implementation - BEGIN
	 */        
	protected void initTopPanel() {
		org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(hidrocon.HidroconApp.class).getContext().getResourceMap(HidroconView.class);
		topPanel.setTitle("  " + resourceMap.getString("routedates.details.toppanel.title"));

		HidroSaveButton saveButton = new HidroSaveButton();
        HidroExitButton exitButton = new HidroExitButton();
  
		saveButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				saveDate();
			}
		});
		exitButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				close();
			}
		});
                
		saveButton.setToolTipText(resourceMap.getString("routedate.toolbar.savebutton.tooltip"));
        exitButton.setToolTipText(resourceMap.getString("routedate.toolbar.exitbutton.tooltip"));

		topPanel.addButton(saveButton);
        topPanel.addButton(exitButton);
	}

    protected void initKeyBinding() {
        
        javax.swing.Action saveAction = new AbstractAction() {
            public void actionPerformed(ActionEvent actionEvent) {
                saveDate();
            }
        };        

        javax.swing.Action closeAction = new AbstractAction() {
            public void actionPerformed(ActionEvent actionEvent) {
                close();
            }
        };            
        SwingUtilities.replaceUIActionMap(mainPanel, null);
        SwingUtilities.replaceUIInputMap(mainPanel, JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT, null);
        
        InputMap inputMap = mainPanel.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);        
        inputMap.put(KeyStroke.getKeyStroke("F11"),"saveDate_F11");
        inputMap.put(KeyStroke.getKeyStroke("F12"),"closeDate_F12");
        mainPanel.getActionMap().put("saveDate_F11",saveAction);
        mainPanel.getActionMap().put("closeDate_F12",closeAction);        
    }

    /*
	 * HidroDialog abstract methods implementation - END
	 */    
	
    private void saveDate() {
        //if (getDate().get)
		dateSaved = true;
        close();
	}
	
    private void close() {
        setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        route = new hidrocon.core.database.route.entities.Route();
        mainPanel = new hidrocon.custom.panel.HidroPanel();
        dateField = new hidrocon.custom.field.HidroDateField();
        calendarButton = new hidrocon.custom.button.HidroCalendarButton();
        dateLabel = new hidrocon.custom.label.HidroLabel();
        topPanel = new hidrocon.custom.panel.HidroTopPanel();

        setBounds(new java.awt.Rectangle(0, 0, 475, 150));
        setName("Form"); // NOI18N

        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setPreferredSize(new java.awt.Dimension(475, 130));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(hidrocon.HidroconApp.class).getContext().getResourceMap(DateSelectionDialog.class);
        dateField.setText(resourceMap.getString("dateField.text")); // NOI18N
        dateField.setName("dateField"); // NOI18N

        calendarButton.setText(resourceMap.getString("calendarButton.text")); // NOI18N
        calendarButton.setName("calendarButton"); // NOI18N

        dateLabel.setText(resourceMap.getString("dateLabel.text")); // NOI18N
        dateLabel.setName("dateLabel"); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calendarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(calendarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        topPanel.setName("topPanel"); // NOI18N
        getContentPane().add(topPanel, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private hidrocon.custom.button.HidroCalendarButton calendarButton;
    private hidrocon.custom.field.HidroDateField dateField;
    private hidrocon.custom.label.HidroLabel dateLabel;
    private hidrocon.custom.panel.HidroPanel mainPanel;
    private hidrocon.core.database.route.entities.Route route;
    private hidrocon.custom.panel.HidroTopPanel topPanel;
    // End of variables declaration//GEN-END:variables
    
    public void clear() {
        dateField.setValue(null);
    }

    public Object getSelection() {
        return (java.util.Date)dateField.getValue();
    }

    public boolean isSelection() {
        return this.dateSaved;
    }
    
}
