/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RouteDetailsDialog.java
 *
 * Created on 29-nov-2011, 7:16:41
 */
package hidrocon.ui.route.dialog;

import hidrocon.core.database.route.entities.Route;
import hidrocon.custom.dialog.HidroDialog;
import hidrocon.custom.dialog.interfaces.IEntityView;
import hidrocon.ui.route.details.RouteDetailsPanelController;
import hidrocon.ui.route.details.RouteDetailsPanelModel;
import hidrocon.ui.route.details.RouteDetailsPanelView;
import java.awt.Dimension;

/**
 *
 * @author David Sáenz Tagarro
 */
public class RouteDetailsDialog extends HidroDialog implements IEntityView {

    private RouteDetailsPanelModel model;    
    private RouteDetailsPanelView view;
    private RouteDetailsPanelController controller;

    /** Creates new form RouteDetailsDialog */
    public RouteDetailsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initContent();
    }
    
    private void initContent() {
        view = new RouteDetailsPanelView();
        model = new RouteDetailsPanelModel();
        controller = new RouteDetailsPanelController(model, view);
        
        controller.setDialog(this);
        view.setMinimumSize(new Dimension(600,150));
        view.setMaximumSize(new Dimension(600,150));
        view.setPreferredSize(new Dimension(600,150));
        getContentPane().add(view);
        
        //HidroBlockingLayerUI layerUI = new HidroBlockingLayerUI();
        //JLayer<JPanel> jlayerMain = new JLayer<JPanel>(view, layerUI);
        //getContentPane().add(jlayerMain);
        pack();        
    }
    
    public void setMode(int mode) {
        view.setMode(mode);
    }

    public void setEntity(Object route) {
        controller.setRoute((Route)route);
    }
    
    public boolean isEntityUpdated() {
        return controller.isRouteSaved(); //administratorSaved;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
