/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RouteBuildingDateDetailsDialog.java
 *
 * Created on 26-nov-2011, 13:33:23
 */
package hidrocon.ui.route.dialog;

import hidrocon.core.database.routedate.entities.RouteDate;
import hidrocon.custom.dialog.interfaces.IEntityView;
import hidrocon.ui.route.routebuildingdate.RouteBuildingDateDetailsController;
import hidrocon.ui.route.routebuildingdate.RouteBuildingDateDetailsModel;
import hidrocon.ui.route.routebuildingdate.RouteBuildingDateDetailsView;
import java.awt.Dimension;

/**
 *
 * @author David Sáenz Tagarro
 */
public class RouteBuildingDateDetailsDialog extends hidrocon.custom.dialog.HidroDialog implements IEntityView {

    private RouteBuildingDateDetailsView view;
    private RouteBuildingDateDetailsModel model;
    private RouteBuildingDateDetailsController controller;
    
    /** Creates new form RouteBuildingDateDetailsDialog */
    public RouteBuildingDateDetailsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initContent();
    }
    
    private void initContent() {
        view = new RouteBuildingDateDetailsView();
        model = new RouteBuildingDateDetailsModel();
        controller = new RouteBuildingDateDetailsController(model, view);
        
        controller.setDialog(this);
        view.setMinimumSize(new Dimension(650,400));
        view.setMaximumSize(new Dimension(650,400));
        view.setPreferredSize(new Dimension(650,400));
        getContentPane().add(view);
        
        //HidroBlockingLayerUI layerUI = new HidroBlockingLayerUI();
        //JLayer<JPanel> jlayerMain = new JLayer<JPanel>(view, layerUI);
        //getContentPane().add(jlayerMain);
        
        pack();        
    }
    
    protected void initTopPanel(){}
    protected void initFocus(){}
    protected void initKeyBinding(){}
    protected void customizeComponents(){}
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /*
     * IEntityView implementation - BEGIN
     */
    public void setMode(int mode) {
        view.setMode(mode);
    }
    
    public void setEntity(Object entity) {
        if (entity instanceof RouteDate) {
            controller.setRouteDate((RouteDate)entity);
        }
    }
    
    public boolean isEntityUpdated() {
        return false; //controller.isEntityUpdated();
    }
    /*
     * IEntityView implementation - END
     */    
}
